config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# 新增一個check的路徑，來供check的方法使用
# member是用來產生路徑的方法，這是block的寫法，有另外的寫法
#使用put方法使用來更新用
  resources :tasks do
      member do
          post :check
      end
  end
  root "tasks#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    # 驗證欄位必須有輸入值
    validates_presence_of :name, :date, :note
    # 限定name欄位的輸入字數為10個字
    validates :name, length: {maximum: 30}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :find_params, only: [:show, :edit, :update, :check]

    def index
      @tasks = Task.order(date: :asc)
    end

    def new
      @task = Task.new
    end

    def create
      @task = Task.new(task_params)
      if @task.save
          flash[:notice] = 'Successfully Created'
          redirect_to action: :index
      else
          render :new
      end
    end

    def show
    end

    def edit
    end

    def update
      if @task.update_attributes(task_params)
          flash[:notice] = 'Successfully Updated'
          redirect_to tasks_path(@task)
      else
          render :edit
      end
    end

    def destroy
      @task = Task.find(params[:id])
      @task.destroy
      flash[:notice] = 'Successfully Deleted'
      redirect_to tasks_url
    end

    def check
      if @task.status == false
          @task.status = true
          @task.update_attributes(check_update)
      else
          @task.status = false
          @task.update_attributes(check_update)
      end

      redirect_to action: :index
    end

    private

    def task_params
      params.require(:task).permit(:name, :date, :note)
    end

    def check_update
      params.permit(:status)
    end

    def find_params
      @task = Task.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
    # todo_check_button用來辨識status的helper，使用在index.html.erb
    # button_checked, button_unchecked是來裝html字串的變數
    def todo_check_button(t)
        if t.status == false
            link_to check_task_path(t), method: :post do
                button_unchecked = '<i class="fa fa-square-o" aria-hidden="true"></i>'
                button_unchecked.html_safe
            end
        else
            link_to check_task_path(t.id), method: :post do
                button_checked = '<i class="fa fa-check-square" aria-hidden="true"></i>'
                button_checked.html_safe
            end
        end
    end
    # todo_edit_button是edit的helper，使用在index.html.erb
    def todo_edit_button(t)
        link_to edit_task_path(t) do
            edit_button = '<i class="fa fa-pencil-square-o" aria-hidden="true"></i>'
            edit_button.html_safe
        end
    end
    # todo_delete_button是delete的helper，使用在index.html.erb
    def overdue?(t)
      if t.date < Date.today
          edit_button = '<i class="fa fa-times" id="overdue" aria-hidden="true" style="color: grey"></i>'
          edit_button.html_safe
      else
          link_to task_path(t), method: :delete, data: { confirm: 'Are you sure?' } do
              edit_button = '<i class="fa fa-times" aria-hidden="true" style="color: red"></i>'
              edit_button.html_safe
          end
      end
    end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="flashmsg">
        <p style="color: green"><%= flash[:notice] %></p>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
    <div class="errorbox alert alert-danger" role="alert">

            <!-- pluralize是個helper，用來顯示一個字串，前面的參數是數字，後面是要顯示的單數名詞，他會自動轉換成複數  -->
            <div>
                <h3>You have <%= pluralize(@task.errors.count, "error") %></h3>
            </div>
            <ul class="list-group">
                <% @task.errors.full_messages.each do |msg|%>
                    <li class="list-group-item">
                        <%= msg%>
                    </li>
                <% end %>
            </ul>

    </div>
<% end %>
    <div class="form-horizontal">
        <%= form_for @task do |f|%>
    <div class="form-group">
        <%= f.label :name, "Name", class: "col-sm-2 control-label"%>
        <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control"%>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :date, "Deadline", class: "col-sm-2 control-label"%>
        <div class="col-sm-10">
            <%= f.text_field :date, class: "form-control"%>
        </div>
    </div>
    <div class="form-group">
        <%= f.label :note, "Note", class: "col-sm-2 control-label"%>
        <div class="col-sm-10">
            <%= f.text_area :note, class: "form-control"%>
        </div>
    </div>
        <%= f.submit button, class: "btn btn-info btn-lg"%>
        <% end %>
        <%= link_to "Back to index", tasks_path%>
    </div>

app/views/tasks/edit.html.erb
<div class="container">
    <h1>Edit Task</h1>
    <%= render partial: 'form', locals: { button: 'Update'}%>
</div>

app/views/tasks/index.html.erb
<div class="container table-responsive">
    <h1>To do list</h1>
    <table class="table table-hover table-condensed">
        <tr>
            <th>Status</th>
            <th>Task</th>
            <th>Deadline</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        <% @tasks.each do |t| %>
            <tr>
                <!-- 狀態，編輯以及刪除的按鈕放入helper，是不要有判斷的工作在view進行 -->
                <td>
                    <%= todo_check_button(t)%>
                </td>
                <!--task name 包含了shoㄊ功能  -->
                <td>
                    <%= link_to t.name, task_path(t), class: "link"%>
                </td>
                <td>
                    <%= t.date%>
                </td>
                <td>
                    <%= todo_edit_button(t) %>
                </td>
                <td>
                    <%= overdue?(t) %>
                </td>
            </tr>
        <% end %>
    </table>

    <%= link_to 'New Task', new_task_path, class: "btn btn-info btn-lg"%>

</div>

app/views/tasks/new.html.erb
<div class="container">
    <h1>New Task</h1>
    <%= render partial: 'form', locals: { button: 'New'}%>
</div>

app/views/tasks/show.html.erb
<div class="showbox">
    <p class="title"><%=@task.name%></p>
    <p class="date-title">Due Date</p>
    <div class="date"><%= @task.date%></div>
    <p class="note-title">Note</p>
    <div class="note"><%= @task.note%></div>

    <div class="showbox_btn">
        <%= todo_edit_button(@task) %>
        <%= link_to "Back to index", tasks_path, class: "show-a"%>
    </div>
</div>